FROM nginx:alpine
WORKDIR /var/www/omg
COPY ./.docker/nginx.dev/nginx.conf /etc/nginx/nginx.conf
RUN rm /etc/nginx/conf.d/*.conf
COPY ./.docker/nginx.dev/conf.d/default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx"]
